[WIP] MacOS 64 Build
djdiskmachine/LittleGPTracker pull request #108
Opened 2024-09-04 15:22 UTC by clsource

This is a work in progress.
I was unable to run the app. But at least it builds.

```
[*ERROR*] Assertion failed: displayModeRet != 0
[*ERROR*]   >> file [/SDLGUIWindowImp.cpp]
[*ERROR*]   >> line 34
```

![imagen](https://github.com/user-attachments/assets/525b8892-8f2a-4654-81a9-b577028a4cc2)

Some changes made to the original xcodeproj file. (It was created a copy so classic OSX can be compiled too)

- Changed to modern macos in deploy target
- added SDL2 and _64BIT to preprocessor flags
- Changed adaptor files to be SDL2 based
- Changed SDL.framework to SDL2.framework
- Added Adapters/MacOS

2024-09-04 17:00 UTC, djdiskmachine commented
Oh wow how exciting to possibly see a macOS build again 🤩

2024-09-04 20:36 UTC, clsource commented
I managed to make it run but required changed the assert.
In MacOS returns 0

The docs tells that it returns 0 on success and negative in error.

https://wiki.libsdl.org/SDL2/SDL_GetDisplayMode

![imagen](https://github.com/user-attachments/assets/d842fe0b-3197-4bff-97df-7e7fc39f4cca)

2024-09-04 21:28 UTC, clsource commented
Ok here is a build for MacOS64
if anyone can test it would be cool.

Was compiled for Macos 10.13 or up

[LittleGPTracker-MacOS64.zip](https://github.com/user-attachments/files/16881167/LittleGPTracker-MacOS64.zip)

2024-09-08 05:17 UTC, djdiskmachine requested changes

2024-09-08 05:17 UTC, djdiskmachine commented on projects/resources/MACOS/config.xml
Since macOS has special handling of app install location, please add fields for SAMPLELIB and ROOTFOLDER
see example here: https://github.com/djdiskmachine/LittleGPTracker/blob/master/projects/resources/CHIP/config.xml#L17

Also, consider adding a line in the LGPTConfiguration.md on how to use this

2024-09-08 05:17 UTC, djdiskmachine commented on sources/Adapters/MacOS/MacOSSystem/MacOSSystem.cpp
Since OSX isn't supported any more, how about we move the OSX files to this new path for MacOSSystem / MacOSMain?

2024-09-08 13:14 UTC, clsource commented on sources/Adapters/MacOS/MacOSSystem/MacOSSystem.cpp
OSX will not be build anymore. But the projects files are needed to be separate and independent so anyone with old mac versions can still build them if they want. 

Lgpt -> OSX32
Lgpt64 -> MacOS64

2024-09-08 15:34 UTC, merged