Platform Makefile Cleanup
djdiskmachine/LittleGPTracker pull request #114
Opened 2024-09-09 07:41 UTC by simotek

* All Platforms now have a defines section at the top to make it easier to see what is enabled in each
* All Platforms now define there platform for consistency
* All Makefiles are in aprox the same order

2024-09-09 07:46 UTC, simotek commented
I was trying to figure out which platforms have midi enabled and this change makes that much easier.

2024-09-09 19:39 UTC, djdiskmachine requested changes

2024-09-09 19:39 UTC, djdiskmachine commented on projects/Makefile.RASPI
> +	-D_NO_JACK_ \
Whitespace before end of line

2024-09-10 17:40 UTC, djdiskmachine approved these changes

2024-09-10 17:46 UTC, merged