added scales
djdiskmachine/LittleGPTracker pull request #128
Opened 2024-09-14 22:28 UTC by clsource

Based on https://github.com/xiphonics/picoTracker/issues/39

2024-09-15 01:24 UTC, clsource commented
closes #119

2024-09-30 17:33 UTC, djdiskmachine requested changes

2024-09-30 17:33 UTC, djdiskmachine commented on sources/Application/Model/Project.cpp
> +    // from: https://github.com/xiphonics/picoTracker/blob/master/sources/Application/Model/Project.cpp
I'd prefer if we keep this info in the corresponding .h and .cpp, it's not necessary to have it here.

2024-09-30 17:33 UTC, djdiskmachine commented on sources/Application/Model/Project.cpp
> +// from: https://github.com/xiphonics/picoTracker/blob/master/sources/Application/Model/Project.cpp
I'd prefer if we keep this info in the corresponding .h and .cpp, it's not necessary to have it here.

2024-09-30 17:33 UTC, djdiskmachine commented on sources/Application/Views/PhraseView.cpp
> +		// from: https://github.com/xiphonics/picoTracker/blob/master/sources/Application/Views/PhraseView.cpp
I'd prefer if we keep this info in the corresponding .h and .cpp, it's not necessary to have it here.

2024-09-30 17:33 UTC, djdiskmachine commented on sources/Application/Views/PhraseView.cpp
> +	// Draw Current Scale
Please no commits containing commented-out code

2024-09-30 17:33 UTC, djdiskmachine commented on sources/Application/Views/ProjectView.cpp
> +	// from: https://github.com/xiphonics/picoTracker/blob/master/sources/Application/Views/ProjectView.cpp
I'd prefer if we keep this info in the corresponding .h and .cpp, it's not necessary to have it here.

2024-10-22 18:34 UTC, djdiskmachine commented
Closed in https://github.com/djdiskmachine/LittleGPTracker/pull/157

2024-10-22 18:34 UTC, closed without merging