Playstation Vita port
djdiskmachine/LittleGPTracker pull request #170
Opened 2024-11-03 20:24 UTC by isage

(this also fixes SDLProcess thread creation for SDL2)

2024-11-04 12:26 UTC, djdiskmachine commented
Thanks for the contribution! Does Vita not play nice with the psp version?

I got a report that soft clipping causes issues on psp1004, have you tried this feature on Vita?

2024-11-04 12:30 UTC, isage commented
> Thanks for the contribution! Does Vita not play nice with the psp version?

Psp version works, but having native one is always better.

> I got a report that soft clipping causes issues on psp1004, have you tried this feature on Vita?

I'm not a musician and know nothing about trackers. How do i check that?

2024-11-10 20:07 UTC, djdiskmachine requested changes

2024-11-10 20:07 UTC, djdiskmachine commented on projects/resources/VITA/sce_sys/icon0.png
Please re-use existing lgpt.png

2024-11-10 20:34 UTC, isage commented on projects/resources/VITA/sce_sys/icon0.png
is there bigger resolution version?

2024-11-10 20:47 UTC, isage commented on projects/resources/VITA/sce_sys/icon0.png
nvm. updated. also updated startup screen artwork to match psp version

2026-04-23 14:32 UTC, closed without merging